import { Page, Text, View, StyleSheet } from '@react-pdf/renderer';

interface Props {
  branding: {
    primaryColor: string;
    orgName: string;
  };
  aboutText: string;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10 },
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  orgName: { fontSize: 24, fontWeight: 'bold', color: '#0F1F1D', marginBottom: 20 },
  divider: { width: 60, height: 2, backgroundColor: '#C9A84C', marginBottom: 20 },
  aboutText: { fontSize: 11, color: '#374151', lineHeight: 1.8, textAlign: 'center', maxWidth: 400 },
  cta: {
    marginTop: 40,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#C9A84C',
    borderRadius: 8,
  },
  ctaText: { fontSize: 12, fontWeight: 'bold', color: '#0F1F1D' },
  footer: { marginTop: 40, fontSize: 8, color: '#9ca3af', textAlign: 'center' },
});

export function AboutPage({ branding, aboutText }: Props) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.container}>
        <Text style={styles.orgName}>{branding.orgName}</Text>
        <View style={styles.divider} />
        <Text style={styles.aboutText}>
          {aboutText || `${branding.orgName} helps businesses build powerful, consistent brands that drive growth. This audit report was prepared using our proprietary brand assessment methodology.`}
        </Text>
        <View style={styles.cta}>
          <Text style={styles.ctaText}>Let&apos;s Transform Your Brand</Text>
        </View>
        <Text style={styles.footer}>
          Generated by SkaleFlow Brand Audit Engine
        </Text>
      </View>
    </Page>
  );
}
