// ============================================================
// Content Templates Seed Data
// Proven post structures: Objective → Content Type → Format → Template
// System-owned — users cannot edit these, only the generated posts
// ============================================================

export interface ContentTemplateSeed {
  content_type: number;
  format: string;
  objective_category: string;
  name: string;
  description: string;
  hook_pattern: string;
  body_structure: string;
  cta_pattern: string;
  caption_template: string | null;
  hashtag_strategy: string | null;
  visual_brief_template: string | null;
  slide_structure: Array<{ slide: number; purpose: string; pattern: string }> | null;
  shot_template: string | null;
  screen_text_template: Array<{ timestamp: string; purpose: string }> | null;
  example_output: Record<string, unknown>;
}

// ── Type 1: Outcome Oriented ──────────────────────────────────────

const outcomeTemplates: ContentTemplateSeed[] = [
  {
    content_type: 1,
    format: 'carousel',
    objective_category: 'growth',
    name: 'Results Showcase Carousel',
    description: 'Share specific metrics and outcomes to build credibility with decision makers',
    hook_pattern: 'Bold metric: "[Specific number/result] in [timeframe]" or "How [client/we] achieved [result]"',
    body_structure: 'Slide 1: Hook headline with the result number → Slides 2-3: The problem/challenge before → Slide 4: What changed (the approach) → Slides 5-6: Step-by-step breakdown → Slide 7: The full results with data → Slide 8: CTA',
    cta_pattern: 'Want similar results? → [action: DM, link, comment keyword]',
    caption_template: 'Context paragraph explaining the result → Key takeaway → CTA → Hashtags',
    hashtag_strategy: '2 brand + 3 industry + 2 result-focused + 1 reach',
    visual_brief_template: 'Clean, data-focused design. Use brand colors. Large numbers on first slide. Charts/graphs where relevant. Consistent layout across slides.',
    slide_structure: [
      { slide: 1, purpose: 'Hook', pattern: 'Big number or result as headline. One line of context.' },
      { slide: 2, purpose: 'Problem', pattern: 'What the situation looked like before. Paint the pain.' },
      { slide: 3, purpose: 'Context', pattern: 'Why traditional approaches failed.' },
      { slide: 4, purpose: 'Approach', pattern: 'What was done differently. The key insight.' },
      { slide: 5, purpose: 'Step 1-2', pattern: 'First tactical steps taken.' },
      { slide: 6, purpose: 'Step 3-4', pattern: 'Next tactical steps with specific details.' },
      { slide: 7, purpose: 'Results', pattern: 'Full data: before vs after. Multiple metrics.' },
      { slide: 8, purpose: 'CTA', pattern: 'Clear next step. What they should do right now.' },
    ],
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'How we generated R291K from R5K ad spend in 30 days',
      hook: 'R291K revenue from R5K spend. Here\'s exactly how we did it.',
      body: 'Most businesses throw money at ads and pray. We did something different...',
    },
  },
  {
    content_type: 1,
    format: 'static',
    objective_category: 'revenue',
    name: 'Proof Screenshot',
    description: 'Share a screenshot or data point that proves results — builds trust for sales',
    hook_pattern: '"[Result] in [timeframe]" with visual proof (screenshot, chart, dashboard)',
    body_structure: 'Visual: The proof (screenshot/metric) → Caption: Context of what this means → Why it matters → CTA aligned to buying',
    cta_pattern: 'Ready for results like this? [Book a call / DM "results" / Link in bio]',
    caption_template: 'One-line context → What this number means → How it happened (2-3 sentences) → CTA',
    hashtag_strategy: '2 brand + 2 results + 3 industry',
    visual_brief_template: 'Screenshot of dashboard/revenue/metrics with brand overlay. Add callout arrows or highlights to key numbers. Brand watermark.',
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'Client revenue milestone screenshot',
      hook: 'Another client just crossed R500K. Started from zero 6 months ago.',
    },
  },
  {
    content_type: 1,
    format: 'reel',
    objective_category: 'revenue',
    name: 'Before/After Results Reel',
    description: 'Quick-hit before/after transformation video for conversion-focused campaigns',
    hook_pattern: '"Everyone said [thing] was impossible. Here\'s what actually happened." or "Before vs After: [timeframe]"',
    body_structure: 'Hook (0-3s): Pattern interrupt with the result → Before (3-8s): What it looked like before → The shift (8-15s): What changed → After (15-25s): The transformation with proof → CTA (25-30s)',
    cta_pattern: 'Your transformation starts with one conversation → [action]',
    caption_template: 'Hook line → Before/after context → Key lesson → CTA',
    hashtag_strategy: '2 brand + 3 transformation + 2 industry + 1 trending',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Shot 1: Direct to camera, state the result boldly → Shot 2: Show the "before" (B-roll or screen recording) → Shot 3: The turning point → Shot 4: Show the "after" with proof → Shot 5: CTA with energy',
    screen_text_template: [
      { timestamp: '0:00-0:03', purpose: 'Hook text overlay — the result' },
      { timestamp: '0:03-0:08', purpose: 'BEFORE label + context' },
      { timestamp: '0:08-0:15', purpose: 'THE SHIFT label' },
      { timestamp: '0:15-0:25', purpose: 'AFTER label + key metrics' },
      { timestamp: '0:25-0:30', purpose: 'CTA text' },
    ],
    example_output: {
      topic: 'Before/after client transformation in 90 days',
      hook: 'Everyone told them LinkedIn was a waste of time. 90 days later...',
    },
  },

  // ── Type 2: Point of View ──────────────────────────────────────

  {
    content_type: 2,
    format: 'text',
    objective_category: 'growth',
    name: 'Contrarian Take',
    description: 'Challenge conventional wisdom to attract like-minded decision makers',
    hook_pattern: '"Most [industry] advice is wrong about [topic]." or "Unpopular opinion: [bold statement]" or "[Common belief]? That\'s exactly why you\'re stuck."',
    body_structure: 'Hook: Bold contrarian statement → Line 2: Why most people get it wrong → Line 3-4: Your actual experience/data → Line 5: The reframe — what you believe instead → Line 6: Why this matters for the reader → CTA: Agree? or What do you think?',
    cta_pattern: 'Agree or disagree? Drop your take below. → [engagement driver]',
    caption_template: null,
    hashtag_strategy: '2 brand + 2 thought-leadership + 2 industry',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'Why most marketing advice keeps you dependent',
      hook: 'Most marketing advice keeps you dependent on the person giving it. Here\'s what nobody tells you...',
      body: 'The marketing industry has a dirty secret:\n\nThe more complex they make it sound, the more you need them.\n\nBut here\'s what I\'ve learned after scaling 50+ brands:\n\nThe best marketing is simple. Painfully simple.\n\n3 things that actually move the needle:\n1. Say what you do, clearly\n2. Show proof it works\n3. Make it easy to buy\n\nThat\'s it. Everything else is noise.\n\nAgree? Or am I oversimplifying?',
    },
  },
  {
    content_type: 2,
    format: 'reel',
    objective_category: 'brand',
    name: 'Hot Take Reel',
    description: 'Direct-to-camera opinion piece to establish thought leadership',
    hook_pattern: '"Stop doing [common thing]. It\'s killing your [result]." or "I lost [something] because I believed [common advice]."',
    body_structure: 'Hook (0-3s): Bold statement, zero preamble → Point (3-15s): Why this belief is wrong → Evidence (15-25s): What you\'ve seen/experienced → Reframe (25-35s): What to do instead → CTA (35-40s)',
    cta_pattern: 'Follow if you agree. Comment if you disagree.',
    caption_template: 'Hook line → Extended context → Your stance → CTA',
    hashtag_strategy: '2 brand + 2 opinion + 2 industry + 2 reach',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Tight frame, direct to camera. No intro. Start mid-sentence or with a bold statement. Confident energy, conversational tone. Cut between angles if possible.',
    screen_text_template: [
      { timestamp: '0:00-0:03', purpose: 'Hook text — the contrarian statement' },
      { timestamp: '0:03-0:15', purpose: 'Key phrase highlight' },
      { timestamp: '0:25-0:35', purpose: 'The reframe — "Instead, do this:"' },
      { timestamp: '0:35-0:40', purpose: 'CTA' },
    ],
    example_output: {
      topic: 'Stop posting motivational quotes',
      hook: 'Stop posting motivational quotes. Your audience doesn\'t need inspiration — they need proof you can help them.',
    },
  },

  // ── Type 3: Authority ──────────────────────────────────────

  {
    content_type: 3,
    format: 'carousel',
    objective_category: 'growth',
    name: 'Framework Breakdown',
    description: 'Share a proprietary framework or methodology to position as expert',
    hook_pattern: '"The [number]-step framework for [desirable outcome]" or "How top [role/industry] think about [topic]"',
    body_structure: 'Slide 1: Framework name + outcome promise → Slides 2-6: One step per slide with explanation → Slide 7: Summary/diagram → Slide 8: CTA',
    cta_pattern: 'Save this for later. Share with someone who needs it.',
    caption_template: 'Why I created this framework → Who it\'s for → Quick overview → Save + Share CTA',
    hashtag_strategy: '2 brand + 3 framework/methodology + 2 industry',
    visual_brief_template: 'Professional, clean. Each slide has a clear heading + 2-3 lines max. Use numbered steps. Brand colors throughout. Final slide: visual diagram of the full framework.',
    slide_structure: [
      { slide: 1, purpose: 'Hook', pattern: 'Framework name as headline. "The X Framework for [outcome]"' },
      { slide: 2, purpose: 'Step 1', pattern: 'First step with brief explanation' },
      { slide: 3, purpose: 'Step 2', pattern: 'Second step with brief explanation' },
      { slide: 4, purpose: 'Step 3', pattern: 'Third step with brief explanation' },
      { slide: 5, purpose: 'Step 4', pattern: 'Fourth step with brief explanation' },
      { slide: 6, purpose: 'Why it works', pattern: 'Brief explanation of why this framework is effective' },
      { slide: 7, purpose: 'Summary', pattern: 'All steps at a glance — visual diagram' },
      { slide: 8, purpose: 'CTA', pattern: 'Save + share + follow for more frameworks' },
    ],
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'The SCALE Framework for content that converts',
      hook: 'The SCALE Framework: 5 steps to content that actually drives revenue (not just likes)',
    },
  },
  {
    content_type: 3,
    format: 'text',
    objective_category: 'community',
    name: 'Lessons Learned Post',
    description: 'Share hard-won lessons from experience to build trust and authority',
    hook_pattern: '"[Number] things I learned [doing X / after Y years / from failing at Z]"',
    body_structure: 'Hook: Number + context → Each lesson as a numbered point (1-2 lines each) → Final lesson is the most impactful → CTA: What lessons would you add?',
    cta_pattern: 'What would you add to this list? → [engagement]',
    caption_template: null,
    hashtag_strategy: '2 brand + 2 lessons + 2 industry',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: '7 lessons from scaling a brand from 0 to 100K followers',
      hook: '7 things nobody told me about growing a brand from scratch:',
    },
  },

  // ── Type 4: How-To ──────────────────────────────────────

  {
    content_type: 4,
    format: 'carousel',
    objective_category: 'community',
    name: 'Step-by-Step Tutorial',
    description: 'Teach a specific skill with actionable steps — high save rate content',
    hook_pattern: '"How to [specific outcome] in [timeframe/steps]" or "The exact process I use to [do X]"',
    body_structure: 'Slide 1: "How to [outcome]" hook → Slides 2-7: One step per slide, clear action → Slide 8: Recap + CTA',
    cta_pattern: 'Save this guide. Follow for more tutorials like this.',
    caption_template: 'Why this matters → Who this is for → Quick list of steps → Save CTA',
    hashtag_strategy: '2 brand + 3 tutorial/howto + 2 industry + 1 reach',
    visual_brief_template: 'Clean instructional design. Numbered steps. Icons or simple illustrations. Screenshots where relevant. Brand colors.',
    slide_structure: [
      { slide: 1, purpose: 'Hook', pattern: '"How to [outcome]" — make the outcome specific and desirable' },
      { slide: 2, purpose: 'Step 1', pattern: 'First action with clear instruction' },
      { slide: 3, purpose: 'Step 2', pattern: 'Second action' },
      { slide: 4, purpose: 'Step 3', pattern: 'Third action' },
      { slide: 5, purpose: 'Step 4', pattern: 'Fourth action' },
      { slide: 6, purpose: 'Step 5', pattern: 'Fifth action' },
      { slide: 7, purpose: 'Pro tip', pattern: 'Bonus tip or common mistake to avoid' },
      { slide: 8, purpose: 'CTA', pattern: 'Save + follow for more' },
    ],
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'How to write LinkedIn posts that get 10x engagement',
      hook: 'How to write LinkedIn posts that actually get engagement (step-by-step):',
    },
  },
  {
    content_type: 4,
    format: 'reel',
    objective_category: 'growth',
    name: 'Quick Tutorial Reel',
    description: 'Fast-paced how-to video for high reach and saves',
    hook_pattern: '"Here\'s how to [specific thing] in [30 seconds / 3 steps]" or "The easiest way to [outcome]"',
    body_structure: 'Hook (0-3s): State what they\'ll learn → Step 1 (3-10s) → Step 2 (10-18s) → Step 3 (18-25s) → Result/CTA (25-30s)',
    cta_pattern: 'Save this for later. Follow for more tips.',
    caption_template: 'Hook → What you\'ll learn → Steps listed → Save CTA',
    hashtag_strategy: '2 brand + 3 tutorial + 2 trending',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Screen recording or direct-to-camera. Fast cuts. No filler. Show, don\'t tell. Each step should be visually clear. End with the finished result.',
    screen_text_template: [
      { timestamp: '0:00-0:03', purpose: 'HOOK: "How to [X] in 30 seconds"' },
      { timestamp: '0:03-0:10', purpose: 'STEP 1: [action]' },
      { timestamp: '0:10-0:18', purpose: 'STEP 2: [action]' },
      { timestamp: '0:18-0:25', purpose: 'STEP 3: [action]' },
      { timestamp: '0:25-0:30', purpose: 'THE RESULT + CTA' },
    ],
    example_output: {
      topic: 'How to write a hook that stops the scroll',
      hook: 'How to write a scroll-stopping hook in 3 steps:',
    },
  },

  // ── Type 5: Community ──────────────────────────────────────

  {
    content_type: 5,
    format: 'text',
    objective_category: 'community',
    name: 'Question / Poll Post',
    description: 'Ask a thought-provoking question to drive comments and engagement',
    hook_pattern: '"What\'s your take on [topic]?" or "Hot take: [statement]. Agree or disagree?" or "[Industry question] — I\'ll go first:"',
    body_structure: 'Hook: Engaging question or statement → Line 2: Brief context or "I\'ll go first" with your answer → Line 3: Why this matters → CTA: "Drop your answer below"',
    cta_pattern: 'Your turn — drop your answer in the comments.',
    caption_template: null,
    hashtag_strategy: '2 brand + 2 discussion + 2 industry',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'Best business advice you ever received',
      hook: 'What\'s the best business advice you\'ve ever received?\n\nI\'ll go first:\n\n"Stop trying to be for everyone. Be the only option for someone."\n\nChanged everything.\n\nYour turn 👇',
    },
  },
  {
    content_type: 5,
    format: 'reel',
    objective_category: 'growth',
    name: 'This or That Reel',
    description: 'Quick comparison/debate format to drive comments',
    hook_pattern: '"[Option A] or [Option B]? There\'s only one right answer." or "Which one are you?"',
    body_structure: 'Hook (0-2s): The choice → Option A (2-8s): Quick case for it → Option B (8-15s): Quick case for it → Your pick (15-20s): What you prefer and why → CTA (20-25s): "Which one? Comment below"',
    cta_pattern: 'Drop your answer in the comments. Which one are you?',
    caption_template: 'The debate → Your stance → Ask for their answer',
    hashtag_strategy: '2 brand + 2 debate + 2 reach',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Split-screen or quick cut between two options. Energetic. Use text labels for each option. End with "?" gesture.',
    screen_text_template: [
      { timestamp: '0:00-0:02', purpose: '[Option A] vs [Option B]' },
      { timestamp: '0:02-0:08', purpose: 'Option A explanation' },
      { timestamp: '0:08-0:15', purpose: 'Option B explanation' },
      { timestamp: '0:15-0:20', purpose: 'Your pick + why' },
      { timestamp: '0:20-0:25', purpose: 'CTA: Comment below!' },
    ],
    example_output: {
      topic: 'Organic vs Paid marketing',
      hook: 'Organic or Paid? There\'s only one right answer for early-stage businesses.',
    },
  },

  // ── Type 6: Culture / Behind the Scenes ──────────────────────────

  {
    content_type: 6,
    format: 'reel',
    objective_category: 'brand',
    name: 'Day in the Life Reel',
    description: 'Show behind the scenes of your work to humanize the brand',
    hook_pattern: '"A day in the life of [role/building X]" or "What it actually looks like to [run/build/do X]"',
    body_structure: 'Hook (0-2s): Context setter → Morning (2-8s): Key morning activity → Midday (8-15s): Core work moments → Afternoon (15-22s): Challenge or win → End (22-28s): Reflection + CTA',
    cta_pattern: 'Follow for more behind-the-scenes content.',
    caption_template: 'Context → What today looked like → Key moment/lesson → Follow CTA',
    hashtag_strategy: '2 brand + 2 bts + 2 culture + 1 day-in-life',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Authentic B-roll throughout the day. Mix of phone footage and setup shots. Natural lighting preferred. Show real work, not staged. Time-lapses for transitions.',
    screen_text_template: [
      { timestamp: '0:00-0:02', purpose: 'Title: "Day in the life of [X]"' },
      { timestamp: '0:02-0:08', purpose: 'Morning context' },
      { timestamp: '0:08-0:15', purpose: 'Key work moment' },
      { timestamp: '0:15-0:22', purpose: 'Challenge or win' },
      { timestamp: '0:22-0:28', purpose: 'Reflection + CTA' },
    ],
    example_output: {
      topic: 'A day building SkaleFlow',
      hook: 'What building a startup actually looks like (no glamour version):',
    },
  },
  {
    content_type: 6,
    format: 'static',
    objective_category: 'community',
    name: 'Team / Culture Spotlight',
    description: 'Highlight a team member, value, or culture moment',
    hook_pattern: '"Meet [person/role]" or "Why we [cultural practice] at [brand]" or "This is what [value] looks like in practice"',
    body_structure: 'Visual: Photo/graphic of team member or culture moment → Caption: Introduction → What makes this special → How it reflects your values → CTA: engagement question',
    cta_pattern: 'What does your team culture look like? Share below.',
    caption_template: 'Introduction → Story/context → What this means to you → Engagement question',
    hashtag_strategy: '2 brand + 2 culture + 2 team + 1 hiring',
    visual_brief_template: 'Authentic photo of team member or workspace. Brand color overlay or frame. Name/role text overlay. Warm, approachable feel.',
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'Team culture: Why we do weekly retros',
      hook: 'Every Friday we do something most startups skip. Here\'s why it matters:',
    },
  },

  // ── Type 7: Trend / Meme ──────────────────────────────────────

  {
    content_type: 7,
    format: 'reel',
    objective_category: 'growth',
    name: 'Trend Ride',
    description: 'Ride a trending audio/format and connect it to your niche for reach',
    hook_pattern: 'Use trending audio/format but twist it → "[Trending setup] but for [your industry/niche]"',
    body_structure: 'Hook (0-2s): Trending format setup → Twist (2-8s): Apply to your industry → Payoff (8-15s): The punchline/insight → Brand connection (15-20s): Quick tie to what you do',
    cta_pattern: 'Follow for more [industry] content that actually makes you laugh.',
    caption_template: 'Setup → Punchline → Tag someone who relates → Follow CTA',
    hashtag_strategy: '2 brand + 2 trending + 2 industry + 2 viral',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Match the trending format exactly. Use trending audio. Quick cuts. Energetic. The brand connection should feel natural, not forced.',
    screen_text_template: [
      { timestamp: '0:00-0:02', purpose: 'Trending setup text' },
      { timestamp: '0:02-0:08', purpose: 'Industry twist' },
      { timestamp: '0:08-0:15', purpose: 'Punchline / payoff' },
    ],
    example_output: {
      topic: 'Trending audio applied to marketing struggles',
      hook: 'POV: You finally found a marketing strategy that works and then the algorithm changes again',
    },
  },
  {
    content_type: 7,
    format: 'static',
    objective_category: 'growth',
    name: 'Industry Meme',
    description: 'Relatable meme format that connects to your industry — high share potential',
    hook_pattern: 'Meme image/format + industry-specific caption. Relatable > clever.',
    body_structure: 'Visual: Meme format (popular template or custom) → Caption: Setup + punchline → Brief brand connection → Share CTA',
    cta_pattern: 'Tag someone who relates. Share this with your team.',
    caption_template: 'Meme context → "Tag someone who..." or "Share if you..." → Brand mention',
    hashtag_strategy: '2 brand + 2 meme + 2 industry + 2 viral',
    visual_brief_template: 'Popular meme template adapted for the industry. Text should be large and readable. Brand watermark subtle. Can be custom illustration in brand style.',
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'When the client says "just make it go viral"',
      hook: 'Client: "Can you just make it go viral?" Me: *stares in strategy*',
    },
  },

  // ── Cross-type: Video formats for multiple types ──────────────

  {
    content_type: 3,
    format: 'video',
    objective_category: 'growth',
    name: 'Expert Explainer Video',
    description: 'In-depth explanation of a concept to position as authority (2-5 min)',
    hook_pattern: '"Most people misunderstand [topic]. Let me explain it properly." or "The truth about [topic] that experts won\'t tell you."',
    body_structure: 'Hook (0-10s): Why this matters → Context (10-30s): Background most people miss → Breakdown (30s-3min): Step-by-step explanation → Key insight (3-4min): The thing that changes everything → CTA (4-5min): Next steps',
    cta_pattern: 'Subscribe for more deep dives. Link in bio for [resource].',
    caption_template: 'Hook → Key points covered → Subscribe CTA',
    hashtag_strategy: '2 brand + 3 expert + 2 topic + 1 education',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: 'Mix of direct-to-camera and supporting visuals/diagrams. Professional lighting. Use B-roll to illustrate points. Add chapter markers.',
    screen_text_template: [
      { timestamp: '0:00-0:10', purpose: 'Hook statement' },
      { timestamp: '0:10-0:30', purpose: 'Context / Why this matters' },
      { timestamp: '0:30-3:00', purpose: 'Key section headings as they appear' },
      { timestamp: '3:00-4:00', purpose: 'KEY INSIGHT highlight' },
      { timestamp: '4:00-5:00', purpose: 'CTA + Subscribe' },
    ],
    example_output: {
      topic: 'Why most content strategies fail',
      hook: 'Your content strategy is probably failing. Not because your content is bad — but because you\'re optimizing for the wrong thing.',
    },
  },
  {
    content_type: 1,
    format: 'text',
    objective_category: 'revenue',
    name: 'Case Study Text Post',
    description: 'Written case study format for LinkedIn — proves results with story',
    hook_pattern: '"[Client type] came to us with [problem]. [Timeframe] later, [result]." or "This one conversation changed [metric] by [%]."',
    body_structure: 'Hook: Result headline → The Problem: What they were dealing with → The Approach: What was done differently → The Result: Specific numbers → The Lesson: What this means for the reader → CTA',
    cta_pattern: 'If you\'re dealing with [similar problem], let\'s talk. [action]',
    caption_template: null,
    hashtag_strategy: '2 brand + 2 case-study + 2 results + 2 industry',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'How a coaching business 3x\'d revenue in 60 days',
      hook: 'A coaching business was stuck at R40K/month. They\'d tried everything.\n\n60 days later? R127K.\n\nHere\'s what we changed:\n\nThe problem wasn\'t their offer. It wasn\'t their audience.\n\nIt was their positioning.\n\nThey were speaking to everyone. Which meant they were speaking to no one.\n\nWe narrowed their ICP to one specific person.\nRewrote every piece of content for that person.\nBuilt a 3-post-per-week engine.\n\nResult: 3x revenue. Same ad spend. Same team.\n\nThe lesson? Specificity scales. Generality doesn\'t.\n\nDealing with the same plateau? DM me "scale" and I\'ll share the framework.',
    },
  },
  {
    content_type: 4,
    format: 'thread',
    objective_category: 'community',
    name: 'Thread Tutorial',
    description: 'Multi-tweet tutorial format for X/Twitter — high bookmark rate',
    hook_pattern: '"Here\'s how to [outcome] (thread 🧵)" or "[Number] steps to [result]:"',
    body_structure: 'Tweet 1: Hook + what they\'ll learn → Tweets 2-8: One step per tweet → Tweet 9: Recap + CTA',
    cta_pattern: 'Bookmark this thread. Repost to help someone. Follow for more.',
    caption_template: null,
    hashtag_strategy: '1 brand + 2 topic',
    visual_brief_template: null,
    slide_structure: null,
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: 'How to build a content system from scratch',
      hook: 'I built a content system that generates 30 posts/month in 2 hours.\n\nHere\'s the exact process (steal it):',
    },
  },
  {
    content_type: 5,
    format: 'carousel',
    objective_category: 'growth',
    name: 'Engagement Carousel',
    description: 'Interactive carousel designed to drive comments and shares',
    hook_pattern: '"Which one are you?" or "[Number] types of [audience] — which one is you?" or "Rate yourself honestly:"',
    body_structure: 'Slide 1: The question/challenge → Slides 2-7: Options/types with fun descriptions → Slide 8: "Which one? Comment your number"',
    cta_pattern: 'Comment your number. Tag someone who\'s #[number].',
    caption_template: 'Context → The question → Comment CTA',
    hashtag_strategy: '2 brand + 2 interactive + 2 fun + 2 reach',
    visual_brief_template: 'Fun, colorful design. Each option should be visually distinct. Use icons/illustrations. Brand colors but playful feel.',
    slide_structure: [
      { slide: 1, purpose: 'Hook', pattern: 'The question or challenge' },
      { slide: 2, purpose: 'Option 1', pattern: 'Type/option with fun description' },
      { slide: 3, purpose: 'Option 2', pattern: 'Type/option with fun description' },
      { slide: 4, purpose: 'Option 3', pattern: 'Type/option with fun description' },
      { slide: 5, purpose: 'Option 4', pattern: 'Type/option with fun description' },
      { slide: 6, purpose: 'Option 5', pattern: 'Type/option with fun description' },
      { slide: 7, purpose: 'Bonus/twist', pattern: 'Unexpected option or "if you\'re none of these..."' },
      { slide: 8, purpose: 'CTA', pattern: '"Comment your number. Tag someone who\'s #X"' },
    ],
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: '5 types of content creators — which one are you?',
      hook: '5 types of content creators.\n\nWhich one are you? (Be honest)',
    },
  },
  {
    content_type: 6,
    format: 'carousel',
    objective_category: 'brand',
    name: 'Values / Mission Carousel',
    description: 'Showcase brand values or mission in a swipeable format',
    hook_pattern: '"Why we exist" or "[Number] things we believe at [brand]" or "This is what [brand] stands for"',
    body_structure: 'Slide 1: "What we believe" hook → Slides 2-6: One value per slide with explanation → Slide 7: Mission statement → Slide 8: Follow CTA',
    cta_pattern: 'If this resonates, you belong here. Follow along.',
    caption_template: 'Why values matter → Overview → Follow CTA',
    hashtag_strategy: '2 brand + 2 values + 2 culture',
    visual_brief_template: 'Bold typography. One value per slide. Brand colors. Clean minimal design. Mission statement slide should feel powerful.',
    slide_structure: [
      { slide: 1, purpose: 'Hook', pattern: '"What we believe" or "Our non-negotiables"' },
      { slide: 2, purpose: 'Value 1', pattern: 'Value name + one-line explanation' },
      { slide: 3, purpose: 'Value 2', pattern: 'Value name + one-line explanation' },
      { slide: 4, purpose: 'Value 3', pattern: 'Value name + one-line explanation' },
      { slide: 5, purpose: 'Value 4', pattern: 'Value name + one-line explanation' },
      { slide: 6, purpose: 'Value 5', pattern: 'Value name + one-line explanation' },
      { slide: 7, purpose: 'Mission', pattern: 'Full mission statement' },
      { slide: 8, purpose: 'CTA', pattern: 'Follow if this resonates' },
    ],
    shot_template: null,
    screen_text_template: null,
    example_output: {
      topic: '5 things we believe at our brand',
      hook: '5 non-negotiable beliefs that drive everything we do:',
    },
  },
];

// ── Combine all templates ──

export const ALL_CONTENT_TEMPLATES: ContentTemplateSeed[] = [
  ...outcomeTemplates,
];
