export interface BrandVariableCategory {
  key: string;
  label: string;
  outputKeys: string[];
}

export const BRAND_VARIABLE_CATEGORIES: BrandVariableCategory[] = [
  {
    key: 'icp',
    label: 'Ideal Client Profile (ICP)',
    outputKeys: [
      'icp_demographics',
      'icp_pains',
      'icp_desires',
      'icp_emotional_triggers',
      'icp_internal_dialogue',
      'icp_objections',
      'icp_psychographics',
      'icp_buying_triggers',
      'customer_journey_stages',
    ],
  },
  {
    key: 'brand',
    label: 'Brand Identity',
    outputKeys: [
      'brand_archetype',
      'brand_characteristics',
      'brand_purpose',
      'brand_values',
      'brand_origin_story',
      'founder_story',
      'category',
    ],
  },
  {
    key: 'enemy',
    label: 'Enemy & Market',
    outputKeys: [
      'enemy_name',
      'enemy_description',
      'enemy_cost',
      'enemy_false_promises',
    ],
  },
  {
    key: 'offer',
    label: 'Offer & Lead Magnet',
    outputKeys: [
      'offer_name',
      'offer_tagline',
      'offer_problem',
      'offer_outcome',
      'offer_transformation_before',
      'offer_transformation_after',
      'offer_inclusions',
      'lead_magnet_type',
      'lead_magnet_title',
      'lead_magnet_promise',
      'lead_magnet_content_outline',
    ],
  },
  {
    key: 'voice',
    label: 'Brand Voice',
    outputKeys: [
      'tone_descriptors',
      'vocabulary_preferred',
      'vocabulary_avoided',
    ],
  },
  {
    key: 'messaging',
    label: 'Messaging & Positioning',
    outputKeys: [
      'message_core',
      'message_pillars',
      'positioning_statement',
      'differentiation_statement',
      'competitive_landscape',
      'beliefs_to_teach',
    ],
  },
  {
    key: 'content',
    label: 'Content Strategy',
    outputKeys: [
      'content_themes',
      'content_pillars',
    ],
  },
  {
    key: 'growth',
    label: 'Growth Engine',
    outputKeys: [
      'authority_pitch',
      'authority_publish_plan',
      'authority_product_ecosystem',
      'authority_profile_plan',
      'authority_partnerships',
      'conversion_business_type',
      'conversion_strategy',
      'conversion_funnel',
      'conversion_metrics',
    ],
  },
];

export const AI_GENERATION_VARIABLES: string[] = BRAND_VARIABLE_CATEGORIES.flatMap(c => c.outputKeys);

export const VARIABLE_DISPLAY_NAMES: Record<string, string> = {
  icp_demographics: 'ICP Demographics',
  icp_pains: 'ICP Pain Points',
  icp_desires: 'ICP Desires',
  icp_emotional_triggers: 'Emotional Triggers',
  icp_internal_dialogue: 'Internal Dialogue',
  icp_objections: 'Common Objections',
  icp_psychographics: 'Psychographics',
  icp_buying_triggers: 'Buying Triggers',
  customer_journey_stages: 'Customer Journey',
  brand_archetype: 'Brand Archetype',
  brand_characteristics: 'Brand Characteristics',
  brand_purpose: 'Brand Purpose',
  brand_values: 'Brand Values',
  brand_origin_story: 'Origin Story',
  founder_story: 'Founder Story',
  category: 'Category',
  enemy_name: 'Enemy Name',
  enemy_description: 'Enemy Description',
  enemy_cost: 'Cost of the Enemy',
  enemy_false_promises: 'False Promises',
  offer_name: 'Offer Name',
  offer_tagline: 'Offer Tagline',
  offer_problem: 'Problem Solved',
  offer_outcome: 'Outcome Delivered',
  offer_transformation_before: 'Before State',
  offer_transformation_after: 'After State',
  offer_inclusions: 'What\'s Included',
  lead_magnet_type: 'Lead Magnet Type',
  lead_magnet_title: 'Lead Magnet Title',
  lead_magnet_promise: 'Lead Magnet Promise',
  lead_magnet_content_outline: 'Lead Magnet Outline',
  tone_descriptors: 'Tone Descriptors',
  vocabulary_preferred: 'Preferred Vocabulary',
  vocabulary_avoided: 'Avoided Vocabulary',
  message_core: 'Core Message',
  message_pillars: 'Message Pillars',
  positioning_statement: 'Positioning Statement',
  differentiation_statement: 'Differentiation Statement',
  competitive_landscape: 'Competitive Landscape',
  beliefs_to_teach: 'Beliefs to Teach',
  content_themes: 'Content Themes',
  content_pillars: 'Content Pillars',
  authority_pitch: 'Authority Pitch',
  authority_publish_plan: 'Publishing Plan',
  authority_product_ecosystem: 'Product Ecosystem',
  authority_profile_plan: 'Profile & PR Plan',
  authority_partnerships: 'Strategic Partnerships',
  conversion_business_type: 'Business Type',
  conversion_strategy: 'Conversion Strategy',
  conversion_funnel: 'Conversion Funnel',
  conversion_metrics: 'Key Metrics',
};
