// ============================================================
// V3 Content Engine — Recycling Engine
// Recycles top-performing content with refreshed hooks
// ============================================================

import type { SupabaseClient } from '@supabase/supabase-js';

// ---- Config ----

const RECYCLING_CONFIG = {
  minPerformancePercentile: 30,  // top 30% of posts
  minAgeDays: 90,                // at least 90 days old
  cooldownDays: 180,             // not recycled in last 180 days
  maxRecycles: 3,                // max times a post can be recycled
};

// ---- Types ----

interface RecyclablePost {
  id: string;
  campaign_id: string;
  adset_id: string;
  organization_id: string;
  content_type: number;
  content_type_name: string;
  platform: string;
  format: string;
  topic: string;
  hook: string;
  body: string;
  cta: string;
  caption: string;
  hashtags: string[];
  visual_brief: string;
  performance: Record<string, number>;
  published_at: string;
  is_winner: boolean;
}

export interface RecycledPostData {
  sourcePostId: string;
  topic: string;
  body: string;
  cta: string;
  caption: string;
  hashtags: string[];
  visual_brief: string;
  content_type: number;
  content_type_name: string;
  platform: string;
  format: string;
}

// ---- Main functions ----

/**
 * Find posts eligible for recycling in an organization.
 */
export async function findRecyclablePosts(
  supabase: SupabaseClient,
  organizationId: string,
  limit: number = 20
): Promise<RecyclablePost[]> {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - RECYCLING_CONFIG.minAgeDays);

  // Get published posts old enough to recycle
  const { data: posts, error } = await supabase
    .from('content_posts')
    .select('id, campaign_id, adset_id, organization_id, content_type, content_type_name, platform, format, topic, hook, body, cta, caption, hashtags, visual_brief, performance, published_at, is_winner')
    .eq('organization_id', organizationId)
    .eq('status', 'published')
    .not('performance', 'eq', '{}')
    .not('topic', 'is', null)
    .not('body', 'is', null)
    .lt('published_at', cutoffDate.toISOString())
    .order('published_at', { ascending: true });

  if (error || !posts || posts.length === 0) return [];

  // Filter out posts that have been recycled too recently or too many times
  const cooldownDate = new Date();
  cooldownDate.setDate(cooldownDate.getDate() - RECYCLING_CONFIG.cooldownDays);

  const { data: recentRecycles } = await supabase
    .from('content_posts')
    .select('recycled_from')
    .eq('organization_id', organizationId)
    .not('recycled_from', 'is', null)
    .gt('created_at', cooldownDate.toISOString());

  const recentlyRecycledIds = new Set((recentRecycles || []).map(r => r.recycled_from));

  // Count total recycles per source post
  const { data: recycleCounts } = await supabase
    .from('content_posts')
    .select('recycled_from')
    .eq('organization_id', organizationId)
    .not('recycled_from', 'is', null);

  const recycleCountMap: Record<string, number> = {};
  for (const r of (recycleCounts || [])) {
    recycleCountMap[r.recycled_from] = (recycleCountMap[r.recycled_from] || 0) + 1;
  }

  // Calculate performance percentile threshold
  const engagementRates = (posts as RecyclablePost[])
    .map(p => p.performance?.engagement_rate || 0)
    .filter(v => v > 0)
    .sort((a, b) => b - a);

  const percentileIdx = Math.floor(engagementRates.length * RECYCLING_CONFIG.minPerformancePercentile / 100);
  const threshold = engagementRates[percentileIdx] || 0;

  // Filter eligible posts
  const eligible = (posts as RecyclablePost[]).filter(p => {
    if (recentlyRecycledIds.has(p.id)) return false;
    if ((recycleCountMap[p.id] || 0) >= RECYCLING_CONFIG.maxRecycles) return false;
    const er = p.performance?.engagement_rate || 0;
    return er >= threshold || p.is_winner;
  });

  // Sort by performance (best first)
  eligible.sort((a, b) => {
    const aEr = a.performance?.engagement_rate || 0;
    const bEr = b.performance?.engagement_rate || 0;
    return bEr - aEr;
  });

  return eligible.slice(0, limit);
}

/**
 * Create a recycled post from a source post.
 * The recycled post gets new hooks (to be generated by AI later).
 */
export async function recyclePost(
  supabase: SupabaseClient,
  sourcePostId: string,
  targetCampaignId: string,
  targetAdsetId: string
): Promise<{ id: string } | null> {
  // Fetch source post
  const { data: source, error: srcError } = await supabase
    .from('content_posts')
    .select('*')
    .eq('id', sourcePostId)
    .single();

  if (srcError || !source) return null;

  // Create recycled post (body preserved, hooks cleared for AI regeneration)
  const { data: recycled, error: insError } = await supabase
    .from('content_posts')
    .insert({
      adset_id: targetAdsetId,
      campaign_id: targetCampaignId,
      organization_id: source.organization_id,
      content_type: source.content_type,
      content_type_name: source.content_type_name,
      objective: source.objective,
      platform: source.platform,
      format: source.format,
      topic: source.topic,
      hook: null, // Will be regenerated
      hook_variations: null,
      body: source.body,
      cta: source.cta,
      caption: source.caption,
      hashtags: source.hashtags,
      visual_brief: source.visual_brief,
      shot_suggestions: source.shot_suggestions,
      slide_content: source.slide_content,
      on_screen_text: source.on_screen_text,
      status: 'idea', // Needs new hook generation
      recycled_from: sourcePostId,
      ai_generated: false,
    })
    .select('id')
    .single();

  if (insError || !recycled) return null;

  return { id: recycled.id };
}

/**
 * Get recycling statistics for an organization.
 */
export async function getRecyclingStats(
  supabase: SupabaseClient,
  organizationId: string
): Promise<{
  totalRecycled: number;
  recyclableCount: number;
}> {
  const { count: totalRecycled } = await supabase
    .from('content_posts')
    .select('id', { count: 'exact', head: true })
    .eq('organization_id', organizationId)
    .not('recycled_from', 'is', null);

  const recyclable = await findRecyclablePosts(supabase, organizationId, 100);

  return {
    totalRecycled: totalRecycled || 0,
    recyclableCount: recyclable.length,
  };
}
